### ISSUE TITLE
Terraform folder pushed as payload for namespace

### ISSUE THREAD

**Issue by timroster** [cloud-native-toolkit/terraform-gitops-namespace#48]
Seeing this new today with `v 1.14.0`:
![Screen Shot 2022-10-14 at 3 06 16 PM](https://user-images.githubusercontent.com/11901914/195957788-d201d4b9-eca6-42c2-918f-0078006a53e5.png)

Reverting to `v 1.13.1` and the expected commit is happening.

This is based off code created by `iascable` from this bom:
```yaml
apiVersion: cloudnativetoolkit.dev/v1alpha1
kind: BillOfMaterial
metadata:
  name: cluster-with-watson-nlp
spec:
  modules:
    - name: ibm-vpc
      version: v1.17.0
    - name: ibm-vpc-subnets
      version: v1.14.0
    - name: ibm-vpc-gateways
      version: v1.10.0
    - name: ibm-ocp-vpc
      version: v1.16.0
    - name: ibm-object-storage
      version: v4.1.0
    - name: argocd-bootstrap
      version: v1.12.0
    - name: gitops-repo
      alias: gitops_repo
      version: v1.22.2
    - name: terraform-gitops-ubi
      alias: terraform_gitops_ubi
      version: v0.0.8
    - name: terraform-gitops-watson-nlp
      alias: terraform_gitops_watson_nlp
      version: v0.0.80
```

This appears to be being caused by the version of `igc` in the `quay.io/cloudnativetoolkit/cli-tools:v1.2-v2.2.11` container which is the one referenced to be used in the `launch.sh` from `iascable` (up to latest version = 2.24.0)
